### PR TITLE
Added all W3C input events to f7-input component. Bumped version.

### PR DESCRIPTION
**Pull request by centrual**
Hello Vladimir,

keypress not working on mobile and i can't cancel keydown event.
beforeinput event required to me, because of this, i updated f7-input component's events. I used W3C docs.

I bumped the version to 0.7.7 and runned `gulp dist` command.

### CODE REVIEW

**Comment by nolimits4web** [comment]
Merged, thanks!

**Comment by nolimits4web** [comment]
By the way, there is a trick for the case you need some native HTML event if there is no such in any component by adding ".native" to the event name. You can add it like <f7-input @blur.native=...>

**Comment by centrual** [comment]
I tested direct events like keydown, but it not linked directly to <input> element, it linked to <div class="item-input">. I didn't tested @blur.native. if it's working with input element, my job completely not required 🤕 i can revert my changes if you want.

Thank you so much for your big efford Vladimir. I really respect you.

**Comment by nolimits4web** [comment]
Ah right, it will link it to component parent element. It is good, no need to revert

**Pull request merged**
