### PR TITLE
Navbar Back Event

### PR DESCRIPTION
**Pull request by bencompton**
When handling route changes from actions (in VueX, Redux, etc.), or in any other scenario where the default routing behavior in F7 core is disabled, having access to a back button click event is useful.

### CODE REVIEW

**Comment by nolimits4web** [comment]
Looks good, what do you think about event naming, i'm trying to find something standardized across framework and thinking about to avoid camel and kebab names of events. What about to change it to `click:back`? Like the events in message:  info-add-streams

**Comment by bencompton** [comment]
Yeah, I like the way it looks in Vue to have them in `verb:noun` format. I think it improves readability: this is what happened, and this is what it happened to. It would be especially nice to have a standard across all components.

In framework7-react, it automatically renames events to be camel-cased and prefixed with "on". So `click:back` would get converted to `onClickBack`, whereas `onBackClick` is more what React users are accustomed to seeing. If I can rely on every component using a standard format  (e.g., `verb-verb:noun-noun-noun`), it won't be a problem at all to reverse the nouns and verbs in React.

**Comment by nolimits4web** [comment]
In F7 and here I've changed most of custom events name to component:event structure like page:init or swipeout:open. And such structure with clicks or default events when it is not really clear from first look what it will be assigned for the whole nav-left or just something internal as it is, as you noticed improves readability. As for the case with React here, I agree onClickBack doesnt look nice. For such case we can emit two events at a time "click:back" and "back-click", what do you think?

**Comment by bencompton** [comment]
One thing I'm not clear on is when the component name comes into play and when it doesn't. For example, if component prefixing were followed strictly, would you expect the event name in this case be `navbar:nav-left:click:back`?

As long as the events are named consistently in Vue, I can automatically pick the strings apart and rename them to whatever for React. For example, if I knew that events were named `parent-component:child-component:action-name:action-target`, and even if sometimes the components were omitted and it was just `action-name:action-target`, as long as the second to last and last colon-delimited values are always action-name and action-target, I would always be able to make the React event be `onActionTargetActionName`

Alternatively, if more than one name were emitted for each event, then I would need to know which ones to ignore. For example, ignore any events with a colon.

**Comment by nolimits4web** [comment]
Sorry, by components i meant F7 components here like Swipeout/Panels/Page, etc. so with such component:event naming they are pretty clear and not confusing and same as DOM events, e.g. http://framework7.io/docs/swipeout.html#swipeout-events. As for the current case, i'm for camelCase events as well but the issue with Vue is that it doesn't support it and will lowercase it and it makes something like `backclick` not really readable option. As for kebab-case, i think it is just not very common to use such naming for events. But anyway, for the current case, let's make it both so we can remove one in future when will agree on something standardized

**Comment by bencompton** [comment]
@nolimits4web - thanks! Both events are fine with me for now--there will just be 2 events in React as well then.

**Pull request merged**
