### PR TITLE
Checkbox / Radio Click Fires Twice

### PR DESCRIPTION
**Pull request by bencompton**
The click event for the ListItem component fires twice when `checkbox` or `radio` are enabled. To reproduce, go into the kitchen sink Forms page, add a breakpoint to the `onClick` method in list-item.vue, then click on a radio button or checkbox and watch `onClick` get called twice.

The reason this is occurring is because radio buttons and checkboxes create an input element nested in a label, and when this parent element gets clicked, the click event fires with the parent element as the target, and then again with the input as a target. Adding `event.preventDefault()` to the `onClick` method in list-item-content.vue would prevent the event from firing on the input, but then the checkbox never appears as checked. Instead, I just added an if statement to only fire the `click` event for the input element.

This fiddle demonstrates the issue:

https://jsfiddle.net/z43qr451/

### CODE REVIEW

**Comment by nolimits4web** [comment]
Well, but this fix it won't work for usual list items, they won't emit click event at all

**Comment by bencompton** [comment]
@nolimits4web - from my tests / understanding, this shouldn't have any effect on normal list items. I changed the `onClick` method of **list-item-content.vue**, and that method only gets called for radio / checkbox within that component. When I go into the kitchen sink and add a breakpoint to `onClick` in list-item.vue, it gets fired as expected when I click on the list items on the main page.

Do you see something I overlooked? If so, my apologies.

**Comment by nolimits4web** [comment]
@bencompton for the case list item is link (has `link` prop) then it is fine and click handler will be attached to parent `<a>` tag, but in case it is not a link (just a list) then click handler is attached to the list-item-content, e.g.:
```html
<f7-list-item title="Hello" @click="doSmth"></f7-list-item>
```
won't work

**Comment by bencompton** [comment]
@nolimits4web - you're right; sorry about that. In the case that the list-item-content is not a radio or a checkbox, I overlooked the fact that it renders a div, and an click event is supposed to get attached to that as well. I'll fix it.

I also noticed that in the case that a list-item is both a link and a checkbox / radio, the click handler also gets fired twice:

```javascript
<f7-list-item title="Content Block" link checkbox></f7-list-item>
```

This may seem like an unusual combination, but I am actually using it that way in an app because the checkbox list items represent multiple-choice questions, and the link chevron on the right side indicates that that a choice follows up to another question.

I'll fix that too.

**Comment by nolimits4web** [comment]
Awesome, thanks

**Pull request merged**
